import type { CardTemplate } from './types';

export const CARD_TEMPLATES: CardTemplate[] = [
  {
    name: 'Chase Sapphire Reserve',
    issuer: 'Chase',
    annualFee: 550,
    color: '#1a3a5c',
    officialBenefitsUrl: 'https://creditcards.chase.com/travel-credit-cards/sapphire/reserve',
    benefits: [
      {
        name: '$300 Annual Travel Credit',
        description: 'Up to $300 in statement credits for travel purchases each year.',
        value: 300,
        frequency: 'annual',
        category: 'travel',
      },
      {
        name: 'Priority Pass Select Membership',
        description: 'Complimentary Priority Pass Select membership for airport lounge access worldwide.',
        value: 429,
        frequency: 'annual',
        category: 'travel',
      },
      {
        name: 'Global Entry / TSA PreCheck Credit',
        description: 'Up to $100 statement credit for Global Entry or $85 for TSA PreCheck every 4 years.',
        value: 100,
        frequency: 'once',
        category: 'travel',
      },
      {
        name: 'DoorDash DashPass',
        description: 'Complimentary DashPass subscription (waived delivery fees).',
        value: 96,
        frequency: 'annual',
        category: 'dining',
      },
      {
        name: 'Primary Rental Car Insurance',
        description: 'Primary auto rental collision damage waiver when you pay with the card.',
        value: 0,
        frequency: 'annual',
        category: 'insurance',
      },
      {
        name: 'Trip Cancellation/Interruption Insurance',
        description: 'Up to $10,000 per person for non-refundable trip costs.',
        value: 0,
        frequency: 'annual',
        category: 'insurance',
      },
      {
        name: 'Lyft Pink Credit',
        description: 'Statement credit on Lyft rides and complimentary Lyft Pink membership.',
        value: 60,
        frequency: 'annual',
        category: 'travel',
      },
    ],
  },
  {
    name: 'Chase Sapphire Preferred',
    issuer: 'Chase',
    annualFee: 95,
    color: '#1e4d8c',
    officialBenefitsUrl: 'https://creditcards.chase.com/travel-credit-cards/sapphire/preferred',
    benefits: [
      {
        name: '$50 Annual Hotel Credit',
        description: 'Up to $50 in annual hotel credits through Chase Travel.',
        value: 50,
        frequency: 'annual',
        category: 'travel',
      },
      {
        name: '$10 Monthly Dining Credit',
        description: '$10 monthly statement credit at select dining partners (DoorDash, etc.).',
        value: 10,
        frequency: 'monthly',
        category: 'dining',
      },
      {
        name: 'DoorDash DashPass',
        description: 'Complimentary DashPass subscription for at least a year.',
        value: 96,
        frequency: 'annual',
        category: 'dining',
      },
      {
        name: 'Trip Cancellation Insurance',
        description: 'Up to $10,000 per person for non-refundable prepaid travel expenses.',
        value: 0,
        frequency: 'annual',
        category: 'insurance',
      },
      {
        name: 'Anniversary Bonus Points',
        description: '10% anniversary bonus on all points earned the previous year.',
        value: 0,
        frequency: 'annual',
        category: 'other',
      },
    ],
  },
  {
    name: 'The Platinum Card® from American Express',
    issuer: 'American Express',
    annualFee: 695,
    color: '#4a4a4a',
    officialBenefitsUrl: 'https://www.americanexpress.com/us/credit-cards/card/platinum/',
    benefits: [
      {
        name: '$200 Airline Fee Credit',
        description: 'Up to $200 in statement credits per calendar year for incidental fees at one selected airline.',
        value: 200,
        frequency: 'annual',
        category: 'travel',
      },
      {
        name: '$200 Hotel Credit',
        description: 'Up to $200 back in statement credits on prepaid Fine Hotels + Resorts or The Hotel Collection bookings.',
        value: 200,
        frequency: 'annual',
        category: 'travel',
      },
      {
        name: '$20 Digital Entertainment Credit',
        description: '$20/month credit for select digital entertainment subscriptions (Disney+, Hulu, ESPN+, Peacock, etc.).',
        value: 20,
        frequency: 'monthly',
        category: 'entertainment',
      },
      {
        name: '$15 Uber Cash',
        description: '$15/month Uber Cash, plus $20 in December. Use for Uber rides or Uber Eats.',
        value: 15,
        frequency: 'monthly',
        category: 'travel',
      },
      {
        name: '$25 Equinox Credit',
        description: '$25/month statement credit for Equinox gym memberships or Equinox+ app.',
        value: 25,
        frequency: 'monthly',
        category: 'other',
      },
      {
        name: '$189 CLEAR Plus Credit',
        description: 'Annual statement credit for CLEAR Plus airport security membership.',
        value: 189,
        frequency: 'annual',
        category: 'travel',
      },
      {
        name: 'Global Entry / TSA PreCheck Credit',
        description: 'Up to $100 credit for Global Entry or $85 for TSA PreCheck every 4.5 years.',
        value: 100,
        frequency: 'once',
        category: 'travel',
      },
      {
        name: 'Centurion Lounge Access',
        description: 'Complimentary access to American Express Centurion Lounges worldwide.',
        value: 0,
        frequency: 'annual',
        category: 'travel',
      },
      {
        name: 'Priority Pass Select Membership',
        description: 'Complimentary Priority Pass Select membership for lounge access.',
        value: 429,
        frequency: 'annual',
        category: 'travel',
      },
      {
        name: '$12.95 Walmart+ Credit',
        description: 'Monthly Walmart+ membership fee covered by statement credit.',
        value: 12.95,
        frequency: 'monthly',
        category: 'shopping',
      },
    ],
  },
  {
    name: 'American Express® Gold Card',
    issuer: 'American Express',
    annualFee: 325,
    color: '#b8860b',
    officialBenefitsUrl: 'https://www.americanexpress.com/us/credit-cards/card/gold-card/',
    benefits: [
      {
        name: '$10 Monthly Dining Credit',
        description: '$10/month credit at Grubhub, The Cheesecake Factory, Goldbelly, Wine.com, and Five Guys.',
        value: 10,
        frequency: 'monthly',
        category: 'dining',
      },
      {
        name: '$10 Monthly Uber Cash',
        description: '$10/month Uber Cash for Uber rides or Uber Eats orders.',
        value: 10,
        frequency: 'monthly',
        category: 'travel',
      },
      {
        name: '$100 Resy Credit',
        description: 'Up to $50 semi-annually in statement credits at US restaurants on Resy.',
        value: 50,
        frequency: 'annual',
        category: 'dining',
      },
      {
        name: '$84 Dunkin\' Credit',
        description: '$7/month statement credit for Dunkin\' purchases.',
        value: 7,
        frequency: 'monthly',
        category: 'dining',
      },
      {
        name: '$100 Hotel Credit',
        description: 'Up to $100 in credits on The Hotel Collection bookings of 2+ nights via Amex Travel.',
        value: 100,
        frequency: 'annual',
        category: 'travel',
      },
    ],
  },
  {
    name: 'Capital One Venture X',
    issuer: 'Capital One',
    annualFee: 395,
    color: '#8b0000',
    officialBenefitsUrl: 'https://www.capitalone.com/credit-cards/venture-x/',
    benefits: [
      {
        name: '$300 Annual Travel Credit',
        description: 'Up to $300 in credits for bookings through Capital One Travel each year.',
        value: 300,
        frequency: 'annual',
        category: 'travel',
      },
      {
        name: '10,000 Anniversary Bonus Miles',
        description: '10,000 bonus miles every year on your account anniversary (worth ~$100).',
        value: 100,
        frequency: 'annual',
        category: 'credit',
      },
      {
        name: 'Capital One Lounge Access',
        description: 'Unlimited access to Capital One Lounges and Plaza Premium Lounges.',
        value: 0,
        frequency: 'annual',
        category: 'travel',
      },
      {
        name: 'Priority Pass Select Membership',
        description: 'Complimentary Priority Pass Select for access to 1,300+ airport lounges.',
        value: 429,
        frequency: 'annual',
        category: 'travel',
      },
      {
        name: 'Global Entry / TSA PreCheck Credit',
        description: 'Up to $100 credit for Global Entry or $85 for TSA PreCheck.',
        value: 100,
        frequency: 'once',
        category: 'travel',
      },
      {
        name: 'Primary Rental Car Insurance',
        description: 'Primary rental car collision damage waiver when paying with the card.',
        value: 0,
        frequency: 'annual',
        category: 'insurance',
      },
    ],
  },
  {
    name: 'Chase Freedom Unlimited',
    issuer: 'Chase',
    annualFee: 0,
    color: '#2d5a27',
    officialBenefitsUrl: 'https://creditcards.chase.com/cash-back-credit-cards/freedom/unlimited',
    benefits: [
      {
        name: 'Purchase Protection',
        description: 'Covers new purchases for 120 days against damage or theft, up to $500 per claim.',
        value: 0,
        frequency: 'annual',
        category: 'insurance',
      },
      {
        name: 'Extended Warranty',
        description: 'Extends the time period of US manufacturer\'s warranty by 1 additional year.',
        value: 0,
        frequency: 'annual',
        category: 'shopping',
      },
      {
        name: 'Trip Cancellation Insurance',
        description: 'Up to $1,500 per person for non-refundable prepaid travel expenses.',
        value: 0,
        frequency: 'annual',
        category: 'insurance',
      },
    ],
  },
  {
    name: 'Citi Premier® Card',
    issuer: 'Citi',
    annualFee: 95,
    color: '#003087',
    officialBenefitsUrl: 'https://www.citi.com/credit-cards/citi-premier-credit-card',
    benefits: [
      {
        name: '$100 Annual Hotel Savings',
        description: 'Up to $100 off a single hotel stay of $500 or more (booked through thankyou.com).',
        value: 100,
        frequency: 'annual',
        category: 'travel',
      },
      {
        name: 'World Elite Concierge',
        description: '24/7 Mastercard World Elite concierge service for travel bookings and more.',
        value: 0,
        frequency: 'annual',
        category: 'travel',
      },
    ],
  },
  {
    name: 'Bank of America® Premium Rewards® Elite',
    issuer: 'Bank of America',
    annualFee: 550,
    color: '#e31837',
    officialBenefitsUrl: 'https://www.bankofamerica.com/credit-cards/products/premium-rewards-elite-credit-card/',
    benefits: [
      {
        name: '$150 Airline Incidental Credit',
        description: 'Up to $150 in statement credits for airline incidental fees annually.',
        value: 150,
        frequency: 'annual',
        category: 'travel',
      },
      {
        name: '$150 Lifestyle Credit',
        description: 'Up to $150 annual credit for eligible streaming, food delivery, and fitness purchases.',
        value: 150,
        frequency: 'annual',
        category: 'entertainment',
      },
      {
        name: 'Priority Pass Select',
        description: 'Complimentary Priority Pass Select membership for lounge access.',
        value: 429,
        frequency: 'annual',
        category: 'travel',
      },
      {
        name: 'Global Entry / TSA PreCheck Credit',
        description: 'Up to $100 for Global Entry or $85 for TSA PreCheck.',
        value: 100,
        frequency: 'once',
        category: 'travel',
      },
    ],
  },
];

export const CUSTOM_CARD_TEMPLATE: CardTemplate = {
  name: 'Custom Card',
  issuer: 'Custom',
  annualFee: 0,
  color: '#374151',
  officialBenefitsUrl: '',
  benefits: [],
};
